/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.chsergeig.shoppy.jooq.enums.Status;
import ru.chsergeig.shoppy.jooq.tables.Order;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> implements Record3<Integer, String, Status> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order.id</code>.
     */
    public OrderRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.order.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.order.info</code>.
     */
    public OrderRecord setInfo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.order.info</code>.
     */
    public String getInfo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.order.status</code>.
     */
    public OrderRecord setStatus(Status value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.order.status</code>.
     */
    public Status getStatus() {
        return (Status) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Status> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Status> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Order.ORDER.ID;
    }

    @Override
    public Field<String> field2() {
        return Order.ORDER.INFO;
    }

    @Override
    public Field<Status> field3() {
        return Order.ORDER.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getInfo();
    }

    @Override
    public Status component3() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getInfo();
    }

    @Override
    public Status value3() {
        return getStatus();
    }

    @Override
    public OrderRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrderRecord value2(String value) {
        setInfo(value);
        return this;
    }

    @Override
    public OrderRecord value3(Status value) {
        setStatus(value);
        return this;
    }

    @Override
    public OrderRecord values(Integer value1, String value2, Status value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Integer id, String info, Status status) {
        super(Order.ORDER);

        setId(id);
        setInfo(info);
        setStatus(status);
    }
}
