/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.chsergeig.shoppy.jooq.tables.UserOrder;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserOrderRecord extends TableRecordImpl<UserOrderRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_order.user_id</code>.
     */
    public UserOrderRecord setUserId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_order.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_order.order_id</code>.
     */
    public UserOrderRecord setOrderId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_order.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserOrder.USER_ORDER.USER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return UserOrder.USER_ORDER.ORDER_ID;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public Integer component2() {
        return getOrderId();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public Integer value2() {
        return getOrderId();
    }

    @Override
    public UserOrderRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserOrderRecord value2(Integer value) {
        setOrderId(value);
        return this;
    }

    @Override
    public UserOrderRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserOrderRecord
     */
    public UserOrderRecord() {
        super(UserOrder.USER_ORDER);
    }

    /**
     * Create a detached, initialised UserOrderRecord
     */
    public UserOrderRecord(Integer userId, Integer orderId) {
        super(UserOrder.USER_ORDER);

        setUserId(userId);
        setOrderId(orderId);
    }
}
