/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.pojos;


import java.io.Serializable;

import ru.chsergeig.shoppy.jooq.enums.Status;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Good implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private Integer article;
    private Status  status;

    public Good() {}

    public Good(Good value) {
        this.id = value.id;
        this.name = value.name;
        this.article = value.article;
        this.status = value.status;
    }

    public Good(
        Integer id,
        String  name,
        Integer article,
        Status  status
    ) {
        this.id = id;
        this.name = name;
        this.article = article;
        this.status = status;
    }

    /**
     * Getter for <code>public.good.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.good.id</code>.
     */
    public Good setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.good.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.good.name</code>.
     */
    public Good setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.good.article</code>.
     */
    public Integer getArticle() {
        return this.article;
    }

    /**
     * Setter for <code>public.good.article</code>.
     */
    public Good setArticle(Integer article) {
        this.article = article;
        return this;
    }

    /**
     * Getter for <code>public.good.status</code>.
     */
    public Status getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.good.status</code>.
     */
    public Good setStatus(Status status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Good (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(article);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
