/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.chsergeig.shoppy.jooq.tables.OrdersGoods;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersGoodsRecord extends TableRecordImpl<OrdersGoodsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orders_goods.order_id</code>.
     */
    public OrdersGoodsRecord setOrderId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.orders_goods.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.orders_goods.good_id</code>.
     */
    public OrdersGoodsRecord setGoodId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.orders_goods.good_id</code>.
     */
    public Integer getGoodId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OrdersGoods.ORDERS_GOODS.ORDER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return OrdersGoods.ORDERS_GOODS.GOOD_ID;
    }

    @Override
    public Integer component1() {
        return getOrderId();
    }

    @Override
    public Integer component2() {
        return getGoodId();
    }

    @Override
    public Integer value1() {
        return getOrderId();
    }

    @Override
    public Integer value2() {
        return getGoodId();
    }

    @Override
    public OrdersGoodsRecord value1(Integer value) {
        setOrderId(value);
        return this;
    }

    @Override
    public OrdersGoodsRecord value2(Integer value) {
        setGoodId(value);
        return this;
    }

    @Override
    public OrdersGoodsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersGoodsRecord
     */
    public OrdersGoodsRecord() {
        super(OrdersGoods.ORDERS_GOODS);
    }

    /**
     * Create a detached, initialised OrdersGoodsRecord
     */
    public OrdersGoodsRecord(Integer orderId, Integer goodId) {
        super(OrdersGoods.ORDERS_GOODS);

        setOrderId(orderId);
        setGoodId(goodId);
    }

    /**
     * Create a detached, initialised OrdersGoodsRecord
     */
    public OrdersGoodsRecord(ru.chsergeig.shoppy.jooq.tables.pojos.OrdersGoods value) {
        super(OrdersGoods.ORDERS_GOODS);

        if (value != null) {
            setOrderId(value.getOrderId());
            setGoodId(value.getGoodId());
        }
    }
}
