/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.chsergeig.shoppy.jooq.tables.User;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_ID_UINDEX = Internal.createIndex(DSL.name("user_id_uindex"), User.USER, new OrderField[] { User.USER.ID }, true);
    public static final Index USER_NAME_UINDEX = Internal.createIndex(DSL.name("user_name_uindex"), User.USER, new OrderField[] { User.USER.NAME }, true);
}
