/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq;


import ru.chsergeig.shoppy.jooq.tables.Good;
import ru.chsergeig.shoppy.jooq.tables.Order;
import ru.chsergeig.shoppy.jooq.tables.OrderGood;
import ru.chsergeig.shoppy.jooq.tables.User;
import ru.chsergeig.shoppy.jooq.tables.UserOrder;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.good</code>.
     */
    public static final Good GOOD = Good.GOOD;

    /**
     * The table <code>public.order</code>.
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * The table <code>public.order_good</code>.
     */
    public static final OrderGood ORDER_GOOD = OrderGood.ORDER_GOOD;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_order</code>.
     */
    public static final UserOrder USER_ORDER = UserOrder.USER_ORDER;
}
