--liquibase formatted sql

--changeset ChSergeiG:add_comments context:ddl
COMMENT ON COLUMN ACCOUNTS.LOGIN IS 'User login';
COMMENT ON COLUMN ACCOUNTS.PASSWORD IS 'Password of the user';
COMMENT ON COLUMN ACCOUNTS.SALTED IS 'Is password salted';
COMMENT ON COLUMN ACCOUNTS.STATUS IS 'User account status';

COMMENT ON COLUMN ACCOUNTS_ORDERS.ACCOUNT_ID IS 'User id';
COMMENT ON COLUMN ACCOUNTS_ORDERS.ORDER_ID IS 'Order id';

COMMENT ON COLUMN ACCOUNTS_ROLES.ACCOUNT_ID IS 'User id';
COMMENT ON COLUMN ACCOUNTS_ROLES.ROLE IS 'Assigned role';

COMMENT ON COLUMN GOODS.NAME IS 'Title of good';
COMMENT ON COLUMN GOODS.ARTICLE IS 'Unique good article';
COMMENT ON COLUMN GOODS.PRICE IS 'Price';
COMMENT ON COLUMN GOODS.STATUS IS 'Given good status';

COMMENT ON COLUMN ORDERS.INFO IS 'Info about order';
COMMENT ON COLUMN ORDERS.STATUS IS 'Order status';
COMMENT ON COLUMN ORDERS.GUID IS 'Unique order guid';

COMMENT ON COLUMN ORDERS_GOODS.ORDER_ID IS 'Order id';
COMMENT ON COLUMN ORDERS_GOODS.GOOD_ID IS 'Good id';
COMMENT ON COLUMN ORDERS_GOODS.COUNT IS 'Count of ordered goods';

--changeset ChSergeiG:create_jwt_storage context:ddl

CREATE TABLE JWT_TOKENS
(
    TOKEN       VARCHAR(2048)            NOT NULL DEFAULT '',
    VALID_UNTIL TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    STATUS      STATUS                   NOT NULL DEFAULT 'ADDED'
);

COMMENT ON COLUMN JWT_TOKENS.TOKEN IS 'Token sha256';
COMMENT ON COLUMN JWT_TOKENS.VALID_UNTIL IS 'Token expiration date';
COMMENT ON COLUMN JWT_TOKENS.STATUS IS 'Token status';
