/**
 * Shoppy
 * Common spec
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommonGoodDto } from './CommonGoodDto';
// import { HttpFile } from '../http/http';

export class OrderEntry {
    'good'?: CommonGoodDto;
    'count'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "good",
            "baseName": "good",
            "type": "CommonGoodDto",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderEntry.attributeTypeMap;
    }

    public constructor() {
    }
}

