/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersGoods implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer orderId;
    private Integer goodId;
    private Long    count;

    public OrdersGoods() {}

    public OrdersGoods(OrdersGoods value) {
        this.orderId = value.orderId;
        this.goodId = value.goodId;
        this.count = value.count;
    }

    public OrdersGoods(
        Integer orderId,
        Integer goodId,
        Long    count
    ) {
        this.orderId = orderId;
        this.goodId = goodId;
        this.count = count;
    }

    /**
     * Getter for <code>public.orders_goods.order_id</code>. Order id
     */
    public Integer getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>public.orders_goods.order_id</code>. Order id
     */
    public OrdersGoods setOrderId(Integer orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Getter for <code>public.orders_goods.good_id</code>. Good id
     */
    public Integer getGoodId() {
        return this.goodId;
    }

    /**
     * Setter for <code>public.orders_goods.good_id</code>. Good id
     */
    public OrdersGoods setGoodId(Integer goodId) {
        this.goodId = goodId;
        return this;
    }

    /**
     * Getter for <code>public.orders_goods.count</code>. Count of ordered goods
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Setter for <code>public.orders_goods.count</code>. Count of ordered goods
     */
    public OrdersGoods setCount(Long count) {
        this.count = count;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrdersGoods (");

        sb.append(orderId);
        sb.append(", ").append(goodId);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
