/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import ru.chsergeig.shoppy.jooq.tables.Accounts;
import ru.chsergeig.shoppy.jooq.tables.AccountsOrders;
import ru.chsergeig.shoppy.jooq.tables.AccountsRoles;
import ru.chsergeig.shoppy.jooq.tables.Goods;
import ru.chsergeig.shoppy.jooq.tables.Orders;
import ru.chsergeig.shoppy.jooq.tables.OrdersGoods;
import ru.chsergeig.shoppy.jooq.tables.records.AccountsOrdersRecord;
import ru.chsergeig.shoppy.jooq.tables.records.AccountsRecord;
import ru.chsergeig.shoppy.jooq.tables.records.AccountsRolesRecord;
import ru.chsergeig.shoppy.jooq.tables.records.GoodsRecord;
import ru.chsergeig.shoppy.jooq.tables.records.OrdersGoodsRecord;
import ru.chsergeig.shoppy.jooq.tables.records.OrdersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountsRecord> ACCOUNT_PK = Internal.createUniqueKey(Accounts.ACCOUNTS, DSL.name("account_pk"), new TableField[] { Accounts.ACCOUNTS.ID }, true);
    public static final UniqueKey<AccountsOrdersRecord> ACCOUNT_ID_ORDER_ID_PK = Internal.createUniqueKey(AccountsOrders.ACCOUNTS_ORDERS, DSL.name("account_id_order_id_pk"), new TableField[] { AccountsOrders.ACCOUNTS_ORDERS.ACCOUNT_ID, AccountsOrders.ACCOUNTS_ORDERS.ORDER_ID }, true);
    public static final UniqueKey<AccountsRolesRecord> ACCOUNT_ID_ROLE_PK = Internal.createUniqueKey(AccountsRoles.ACCOUNTS_ROLES, DSL.name("account_id_role_pk"), new TableField[] { AccountsRoles.ACCOUNTS_ROLES.ACCOUNT_ID, AccountsRoles.ACCOUNTS_ROLES.ROLE }, true);
    public static final UniqueKey<GoodsRecord> GOOD_PK = Internal.createUniqueKey(Goods.GOODS, DSL.name("good_pk"), new TableField[] { Goods.GOODS.ID }, true);
    public static final UniqueKey<OrdersRecord> ORDER_PK = Internal.createUniqueKey(Orders.ORDERS, DSL.name("order_pk"), new TableField[] { Orders.ORDERS.ID }, true);
    public static final UniqueKey<OrdersGoodsRecord> ORDER_ID_GOOD_ID_PK = Internal.createUniqueKey(OrdersGoods.ORDERS_GOODS, DSL.name("order_id_good_id_pk"), new TableField[] { OrdersGoods.ORDERS_GOODS.ORDER_ID, OrdersGoods.ORDERS_GOODS.GOOD_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AccountsOrdersRecord, OrdersRecord> ACCOUNTS_ORDERS__ACCOUNTS_ORDERS_ORDER_ID_FKEY = Internal.createForeignKey(AccountsOrders.ACCOUNTS_ORDERS, DSL.name("accounts_orders_order_id_fkey"), new TableField[] { AccountsOrders.ACCOUNTS_ORDERS.ORDER_ID }, Keys.ORDER_PK, new TableField[] { Orders.ORDERS.ID }, true);
    public static final ForeignKey<OrdersGoodsRecord, GoodsRecord> ORDERS_GOODS__ORDERS_GOODS_GOOD_ID_FKEY = Internal.createForeignKey(OrdersGoods.ORDERS_GOODS, DSL.name("orders_goods_good_id_fkey"), new TableField[] { OrdersGoods.ORDERS_GOODS.GOOD_ID }, Keys.GOOD_PK, new TableField[] { Goods.GOODS.ID }, true);
    public static final ForeignKey<OrdersGoodsRecord, OrdersRecord> ORDERS_GOODS__ORDERS_GOODS_ORDER_ID_FKEY = Internal.createForeignKey(OrdersGoods.ORDERS_GOODS, DSL.name("orders_goods_order_id_fkey"), new TableField[] { OrdersGoods.ORDERS_GOODS.ORDER_ID }, Keys.ORDER_PK, new TableField[] { Orders.ORDERS.ID }, true);
}
