/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.accounts_id_seq</code>
     */
    public static final Sequence<Integer> ACCOUNTS_ID_SEQ = Internal.createSequence("accounts_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.accounts_orders_account_id_seq</code>
     */
    public static final Sequence<Integer> ACCOUNTS_ORDERS_ACCOUNT_ID_SEQ = Internal.createSequence("accounts_orders_account_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.accounts_orders_order_id_seq</code>
     */
    public static final Sequence<Integer> ACCOUNTS_ORDERS_ORDER_ID_SEQ = Internal.createSequence("accounts_orders_order_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.accounts_roles_account_id_seq</code>
     */
    public static final Sequence<Integer> ACCOUNTS_ROLES_ACCOUNT_ID_SEQ = Internal.createSequence("accounts_roles_account_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.goods_id_seq</code>
     */
    public static final Sequence<Integer> GOODS_ID_SEQ = Internal.createSequence("goods_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.orders_goods_good_id_seq</code>
     */
    public static final Sequence<Integer> ORDERS_GOODS_GOOD_ID_SEQ = Internal.createSequence("orders_goods_good_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.orders_goods_order_id_seq</code>
     */
    public static final Sequence<Integer> ORDERS_GOODS_ORDER_ID_SEQ = Internal.createSequence("orders_goods_order_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.orders_id_seq</code>
     */
    public static final Sequence<Integer> ORDERS_ID_SEQ = Internal.createSequence("orders_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
