version: '3'
services:
  postgres:
    image: postgres:13.2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shoppy" ]
      interval: 5s
      timeout: 10s
      retries: 2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shoppy
      - POSTGRES_USER=shoppy
      - POSTGRES_PASSWORD=shoppy
  backend:
    image: chsergeig/shoppy-back:latest
    healthcheck:
      test: [ "CMD-SHELL", "wget -nv --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shoppy
      - SPRING_DATASOURCE_USERNAME=shoppy
      - SPRING_DATASOURCE_PASSWORD=shoppy
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/shoppy
      - SPRING_LIQUIBASE_USER=shoppy
      - SPRING_LIQUIBASE_PASSWORD=shoppy
  frontend:
    image: chsergeig/shoppy-front:latest
    healthcheck:
      test: [ "CMD-SHELL", "service nginx status || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - ./nginx.frontend.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/mime.types
  nginx:
    image: nginx:latest
    healthcheck:
      test: [ "CMD-SHELL", "service nginx status || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/mime.types
