version: '3'
services:
  postgres:
    image: postgres:13.2
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U shoppy" ]
      interval: 5s
      timeout: 10s
      retries: 2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shoppy
      - POSTGRES_USER=shoppy
      - POSTGRES_PASSWORD=shoppy
