/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.daos;


import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

import ru.chsergeig.shoppy.jooq.tables.AccountsOrders;
import ru.chsergeig.shoppy.jooq.tables.records.AccountsOrdersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountsOrdersDao extends DAOImpl<AccountsOrdersRecord, ru.chsergeig.shoppy.jooq.tables.pojos.AccountsOrders, Record2<Integer, Integer>> {

    /**
     * Create a new AccountsOrdersDao without any configuration
     */
    public AccountsOrdersDao() {
        super(AccountsOrders.ACCOUNTS_ORDERS, ru.chsergeig.shoppy.jooq.tables.pojos.AccountsOrders.class);
    }

    /**
     * Create a new AccountsOrdersDao with an attached configuration
     */
    public AccountsOrdersDao(Configuration configuration) {
        super(AccountsOrders.ACCOUNTS_ORDERS, ru.chsergeig.shoppy.jooq.tables.pojos.AccountsOrders.class, configuration);
    }

    @Override
    public Record2<Integer, Integer> getId(ru.chsergeig.shoppy.jooq.tables.pojos.AccountsOrders object) {
        return compositeKeyRecord(object.getAccountId(), object.getOrderId());
    }

    /**
     * Fetch records that have <code>account_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.AccountsOrders> fetchRangeOfAccountId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AccountsOrders.ACCOUNTS_ORDERS.ACCOUNT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>account_id IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.AccountsOrders> fetchByAccountId(Integer... values) {
        return fetch(AccountsOrders.ACCOUNTS_ORDERS.ACCOUNT_ID, values);
    }

    /**
     * Fetch records that have <code>order_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.AccountsOrders> fetchRangeOfOrderId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AccountsOrders.ACCOUNTS_ORDERS.ORDER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>order_id IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.AccountsOrders> fetchByOrderId(Integer... values) {
        return fetch(AccountsOrders.ACCOUNTS_ORDERS.ORDER_ID, values);
    }
}
