/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.daos;


import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ru.chsergeig.shoppy.jooq.enums.Status;
import ru.chsergeig.shoppy.jooq.tables.Goods;
import ru.chsergeig.shoppy.jooq.tables.records.GoodsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsDao extends DAOImpl<GoodsRecord, ru.chsergeig.shoppy.jooq.tables.pojos.Goods, Integer> {

    /**
     * Create a new GoodsDao without any configuration
     */
    public GoodsDao() {
        super(Goods.GOODS, ru.chsergeig.shoppy.jooq.tables.pojos.Goods.class);
    }

    /**
     * Create a new GoodsDao with an attached configuration
     */
    public GoodsDao(Configuration configuration) {
        super(Goods.GOODS, ru.chsergeig.shoppy.jooq.tables.pojos.Goods.class, configuration);
    }

    @Override
    public Integer getId(ru.chsergeig.shoppy.jooq.tables.pojos.Goods object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Goods> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Goods.GOODS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Goods> fetchById(Integer... values) {
        return fetch(Goods.GOODS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ru.chsergeig.shoppy.jooq.tables.pojos.Goods fetchOneById(Integer value) {
        return fetchOne(Goods.GOODS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ru.chsergeig.shoppy.jooq.tables.pojos.Goods> fetchOptionalById(Integer value) {
        return fetchOptional(Goods.GOODS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Goods> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Goods.GOODS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Goods> fetchByName(String... values) {
        return fetch(Goods.GOODS.NAME, values);
    }

    /**
     * Fetch records that have <code>article BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Goods> fetchRangeOfArticle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Goods.GOODS.ARTICLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>article IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Goods> fetchByArticle(String... values) {
        return fetch(Goods.GOODS.ARTICLE, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Goods> fetchRangeOfStatus(Status lowerInclusive, Status upperInclusive) {
        return fetchRange(Goods.GOODS.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Goods> fetchByStatus(Status... values) {
        return fetch(Goods.GOODS.STATUS, values);
    }
}
