/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import ru.chsergeig.shoppy.jooq.enums.Status;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Goods implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer    id;
    private String     name;
    private String     article;
    private BigDecimal price;
    private Status     status;

    public Goods() {}

    public Goods(Goods value) {
        this.id = value.id;
        this.name = value.name;
        this.article = value.article;
        this.price = value.price;
        this.status = value.status;
    }

    public Goods(
        Integer    id,
        String     name,
        String     article,
        BigDecimal price,
        Status     status
    ) {
        this.id = id;
        this.name = name;
        this.article = article;
        this.price = price;
        this.status = status;
    }

    /**
     * Getter for <code>public.goods.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.goods.id</code>.
     */
    public Goods setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.goods.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.goods.name</code>.
     */
    public Goods setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.goods.article</code>.
     */
    public String getArticle() {
        return this.article;
    }

    /**
     * Setter for <code>public.goods.article</code>.
     */
    public Goods setArticle(String article) {
        this.article = article;
        return this;
    }

    /**
     * Getter for <code>public.goods.price</code>.
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>public.goods.price</code>.
     */
    public Goods setPrice(BigDecimal price) {
        this.price = price;
        return this;
    }

    /**
     * Getter for <code>public.goods.status</code>.
     */
    public Status getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.goods.status</code>.
     */
    public Goods setStatus(Status status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Goods (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(article);
        sb.append(", ").append(price);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
