/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersGoods implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer orderId;
    private Integer goodId;

    public OrdersGoods() {}

    public OrdersGoods(OrdersGoods value) {
        this.orderId = value.orderId;
        this.goodId = value.goodId;
    }

    public OrdersGoods(
        Integer orderId,
        Integer goodId
    ) {
        this.orderId = orderId;
        this.goodId = goodId;
    }

    /**
     * Getter for <code>public.orders_goods.order_id</code>.
     */
    public Integer getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>public.orders_goods.order_id</code>.
     */
    public OrdersGoods setOrderId(Integer orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Getter for <code>public.orders_goods.good_id</code>.
     */
    public Integer getGoodId() {
        return this.goodId;
    }

    /**
     * Setter for <code>public.orders_goods.good_id</code>.
     */
    public OrdersGoods setGoodId(Integer goodId) {
        this.goodId = goodId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrdersGoods (");

        sb.append(orderId);
        sb.append(", ").append(goodId);

        sb.append(")");
        return sb.toString();
    }
}
