/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.pojos;


import java.io.Serializable;

import ru.chsergeig.shoppy.jooq.enums.Status;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  info;
    private Status  status;
    private String  guid;

    public Orders() {}

    public Orders(Orders value) {
        this.id = value.id;
        this.info = value.info;
        this.status = value.status;
        this.guid = value.guid;
    }

    public Orders(
        Integer id,
        String  info,
        Status  status,
        String  guid
    ) {
        this.id = id;
        this.info = info;
        this.status = status;
        this.guid = guid;
    }

    /**
     * Getter for <code>public.orders.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.orders.id</code>.
     */
    public Orders setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.orders.info</code>. Info about order
     */
    public String getInfo() {
        return this.info;
    }

    /**
     * Setter for <code>public.orders.info</code>. Info about order
     */
    public Orders setInfo(String info) {
        this.info = info;
        return this;
    }

    /**
     * Getter for <code>public.orders.status</code>. Order status
     */
    public Status getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.orders.status</code>. Order status
     */
    public Orders setStatus(Status status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.orders.guid</code>. Unique order guid
     */
    public String getGuid() {
        return this.guid;
    }

    /**
     * Setter for <code>public.orders.guid</code>. Unique order guid
     */
    public Orders setGuid(String guid) {
        this.guid = guid;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(id);
        sb.append(", ").append(info);
        sb.append(", ").append(status);
        sb.append(", ").append(guid);

        sb.append(")");
        return sb.toString();
    }
}
