/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String  name;
    private final String  password;

    public Users(Users value) {
        this.id = value.id;
        this.name = value.name;
        this.password = value.password;
    }

    public Users(
        Integer id,
        String  name,
        String  password
    ) {
        this.id = id;
        this.name = name;
        this.password = password;
    }

    /**
     * Getter for <code>public.Users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.Users.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.Users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
