spring:
  datasource:
    name: pgShoppy
    generateUniqueName: false
    url: jdbc:postgresql://localhost:5432/shoppy
    username: shoppy
    password: shoppy
    platform: all
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/liquibase/main.xml
    driver-class-name: org.postgresql.Driver
    user: shoppy
    password: shoppy
    contexts: dml, ddl
    url: jdbc:postgresql://localhost:5432/shoppy
  spring:
    jooq:
      sql-dialect: Postgres