server:
  port: 8080
  tomcat:
    threads:
      max: 100
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    name: pgShoppy
    generateUniqueName: false
    url: jdbc:postgresql://localhost:5432/shoppy
    username: shoppy
    password: shoppy
    platform: all
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/liquibase/main.xml
    driver-class-name: org.postgresql.Driver
    user: shoppy
    password: shoppy
    contexts: dml, ddl
    url: jdbc:postgresql://localhost:5432/shoppy
#  jooq:
#    sql-dialect: Postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: health,info
