server:
  port: 8080
  tomcat:
    threads:
      max: 100
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    default: dev
  datasource:
    name: pgShoppy
    generateUniqueName: false
    url: jdbc:postgresql://localhost:5432/shoppy
    username: shoppy
    password: shoppy
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/liquibase/main.xml
    driver-class-name: org.postgresql.Driver
    user: shoppy
    password: shoppy
    contexts: dml, ddl
    url: jdbc:postgresql://localhost:5432/shoppy
  jooq:
    sql-dialect: POSTGRES
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

shoppy:
  security:
    jwt:
      authorization-header: 'X-Authorization'
      # should be stored safely as can be used to decrypt jwt tokens
      # here is only an example
      secret: 'lecD0V5LD8iGBqZ98RrYKs9YVRCxFo5UZV7u6QJNemSpv9SPZB5lqswhEkranZCi'
      expiration-in-seconds: 86400
    user:
      login: 'admin'
      password: 'password'
