/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.chsergeig.shoppy.jooq.tables.Users;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_ID_UINDEX = Internal.createIndex(DSL.name("users_id_uindex"), Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    public static final Index USERS_NAME_UINDEX = Internal.createIndex(DSL.name("users_name_uindex"), Users.USERS, new OrderField[] { Users.USERS.NAME }, true);
}
