/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.chsergeig.shoppy.jooq.tables.Good;
import ru.chsergeig.shoppy.jooq.tables.Order;
import ru.chsergeig.shoppy.jooq.tables.OrderGood;
import ru.chsergeig.shoppy.jooq.tables.User;
import ru.chsergeig.shoppy.jooq.tables.UserOrder;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.good</code>.
     */
    public final Good GOOD = Good.GOOD;

    /**
     * The table <code>public.order</code>.
     */
    public final Order ORDER = Order.ORDER;

    /**
     * The table <code>public.order_good</code>.
     */
    public final OrderGood ORDER_GOOD = OrderGood.ORDER_GOOD;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>public.user_order</code>.
     */
    public final UserOrder USER_ORDER = UserOrder.USER_ORDER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.GOOD_ID_SEQ,
            Sequences.ORDER_GOOD_GOOD_ID_SEQ,
            Sequences.ORDER_GOOD_ORDER_ID_SEQ,
            Sequences.ORDER_ID_SEQ,
            Sequences.USER_ID_SEQ,
            Sequences.USER_ORDER_ORDER_ID_SEQ,
            Sequences.USER_ORDER_USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Good.GOOD,
            Order.ORDER,
            OrderGood.ORDER_GOOD,
            User.USER,
            UserOrder.USER_ORDER);
    }
}
