/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq;


import ru.chsergeig.shoppy.jooq.tables.Accounts;
import ru.chsergeig.shoppy.jooq.tables.AccountsOrders;
import ru.chsergeig.shoppy.jooq.tables.AccountsRoles;
import ru.chsergeig.shoppy.jooq.tables.Goods;
import ru.chsergeig.shoppy.jooq.tables.JwtTokens;
import ru.chsergeig.shoppy.jooq.tables.Orders;
import ru.chsergeig.shoppy.jooq.tables.OrdersGoods;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.accounts</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>public.accounts_orders</code>.
     */
    public static final AccountsOrders ACCOUNTS_ORDERS = AccountsOrders.ACCOUNTS_ORDERS;

    /**
     * The table <code>public.accounts_roles</code>.
     */
    public static final AccountsRoles ACCOUNTS_ROLES = AccountsRoles.ACCOUNTS_ROLES;

    /**
     * The table <code>public.goods</code>.
     */
    public static final Goods GOODS = Goods.GOODS;

    /**
     * The table <code>public.jwt_tokens</code>.
     */
    public static final JwtTokens JWT_TOKENS = JwtTokens.JWT_TOKENS;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.orders_goods</code>.
     */
    public static final OrdersGoods ORDERS_GOODS = OrdersGoods.ORDERS_GOODS;
}
