/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq;


import ru.chsergeig.shoppy.jooq.tables.Databasechangeloglock;
import ru.chsergeig.shoppy.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.Users</code>.
     */
    public static final Users USERS = Users.USERS;
}
