/*
 * This file is generated by jOOQ.
 */
package ru.chsergeig.shoppy.jooq.tables.daos;


import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import ru.chsergeig.shoppy.jooq.enums.Status;
import ru.chsergeig.shoppy.jooq.tables.Orders;
import ru.chsergeig.shoppy.jooq.tables.records.OrdersRecord;

import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersDao extends DAOImpl<OrdersRecord, ru.chsergeig.shoppy.jooq.tables.pojos.Orders, Integer> {

    /**
     * Create a new OrdersDao without any configuration
     */
    public OrdersDao() {
        super(Orders.ORDERS, ru.chsergeig.shoppy.jooq.tables.pojos.Orders.class);
    }

    /**
     * Create a new OrdersDao with an attached configuration
     */
    public OrdersDao(Configuration configuration) {
        super(Orders.ORDERS, ru.chsergeig.shoppy.jooq.tables.pojos.Orders.class, configuration);
    }

    @Override
    public Integer getId(ru.chsergeig.shoppy.jooq.tables.pojos.Orders object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Orders> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Orders.ORDERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Orders> fetchById(Integer... values) {
        return fetch(Orders.ORDERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ru.chsergeig.shoppy.jooq.tables.pojos.Orders fetchOneById(Integer value) {
        return fetchOne(Orders.ORDERS.ID, value);
    }

    /**
     * Fetch records that have <code>info BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Orders> fetchRangeOfInfo(String lowerInclusive, String upperInclusive) {
        return fetchRange(Orders.ORDERS.INFO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>info IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Orders> fetchByInfo(String... values) {
        return fetch(Orders.ORDERS.INFO, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Orders> fetchRangeOfStatus(Status lowerInclusive, Status upperInclusive) {
        return fetchRange(Orders.ORDERS.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Orders> fetchByStatus(Status... values) {
        return fetch(Orders.ORDERS.STATUS, values);
    }

    /**
     * Fetch records that have <code>guid BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Orders> fetchRangeOfGuid(String lowerInclusive, String upperInclusive) {
        return fetchRange(Orders.ORDERS.GUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>guid IN (values)</code>
     */
    public List<ru.chsergeig.shoppy.jooq.tables.pojos.Orders> fetchByGuid(String... values) {
        return fetch(Orders.ORDERS.GUID, values);
    }
}
